// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// TodosCreateTodo implements Todos_createTodo operation.
//
// POST /todos
func (UnimplementedHandler) TodosCreateTodo(ctx context.Context, req *RequestTodo) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// TodosDeleteTodo implements Todos_deleteTodo operation.
//
// DELETE /todos/{todoID}
func (UnimplementedHandler) TodosDeleteTodo(ctx context.Context, params TodosDeleteTodoParams) error {
	return ht.ErrNotImplemented
}

// TodosGetTodo implements Todos_getTodo operation.
//
// GET /todos/{todoID}
func (UnimplementedHandler) TodosGetTodo(ctx context.Context, params TodosGetTodoParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// TodosListTodos implements Todos_listTodos operation.
//
// GET /todos
func (UnimplementedHandler) TodosListTodos(ctx context.Context) (r []Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// TodosUpdateTodo implements Todos_updateTodo operation.
//
// PUT /todos/{todoID}
func (UnimplementedHandler) TodosUpdateTodo(ctx context.Context, req *Todo, params TodosUpdateTodoParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}
