// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// TodosDeleteTodoParams is parameters of Todos_deleteTodo operation.
type TodosDeleteTodoParams struct {
	TodoID int64
}

func unpackTodosDeleteTodoParams(packed middleware.Parameters) (params TodosDeleteTodoParams) {
	{
		key := middleware.ParameterKey{
			Name: "todoID",
			In:   "path",
		}
		params.TodoID = packed[key].(int64)
	}
	return params
}

func decodeTodosDeleteTodoParams(args [1]string, argsEscaped bool, r *http.Request) (params TodosDeleteTodoParams, _ error) {
	// Decode path: todoID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "todoID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TodoID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "todoID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TodosGetTodoParams is parameters of Todos_getTodo operation.
type TodosGetTodoParams struct {
	TodoID int64
}

func unpackTodosGetTodoParams(packed middleware.Parameters) (params TodosGetTodoParams) {
	{
		key := middleware.ParameterKey{
			Name: "todoID",
			In:   "path",
		}
		params.TodoID = packed[key].(int64)
	}
	return params
}

func decodeTodosGetTodoParams(args [1]string, argsEscaped bool, r *http.Request) (params TodosGetTodoParams, _ error) {
	// Decode path: todoID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "todoID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TodoID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "todoID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TodosUpdateTodoParams is parameters of Todos_updateTodo operation.
type TodosUpdateTodoParams struct {
	TodoID int64
}

func unpackTodosUpdateTodoParams(packed middleware.Parameters) (params TodosUpdateTodoParams) {
	{
		key := middleware.ParameterKey{
			Name: "todoID",
			In:   "path",
		}
		params.TodoID = packed[key].(int64)
	}
	return params
}

func decodeTodosUpdateTodoParams(args [1]string, argsEscaped bool, r *http.Request) (params TodosUpdateTodoParams, _ error) {
	// Decode path: todoID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "todoID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.TodoID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "todoID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
