// Code generated by ogen, DO NOT EDIT.

package rest

// OperationName is the ogen operation name
type OperationName = string

const (
	TodosCreateTodoOperation OperationName = "TodosCreateTodo"
	TodosDeleteTodoOperation OperationName = "TodosDeleteTodo"
	TodosGetTodoOperation    OperationName = "TodosGetTodo"
	TodosListTodosOperation  OperationName = "TodosListTodos"
	TodosUpdateTodoOperation OperationName = "TodosUpdateTodo"
)
